package plccom;

import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.GregorianCalendar;
import java.util.Timer;
import java.util.TimerTask;
import java.util.logging.Level;
import java.util.logging.Logger;

import javax.swing.JOptionPane;

import PLCCom.BasicInfoResult;
import PLCCom.CPUModeInfoResult;
import PLCCom.ConnectResult;
import PLCCom.LEDInfoResult;
import PLCCom.OperationResult;
import PLCCom.ReadItemRequest;
import PLCCom.ReadItemRequestCollection;
import PLCCom.ReadItemResult;
import PLCCom.ReadItemResultCollection;
import PLCCom.ReadRequest;
import PLCCom.ReadResult;
import PLCCom.TCP_ISO_Device;
import PLCCom.WriteRequest;
import PLCCom.WriteResult;
import PLCCom.authentication;
import PLCCom.eDataType;
import PLCCom.ePLCType;
import PLCCom.eRegion;

/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * frmTCP.java
 *
 * Created on 17.11.2009, 11:04:59
 */
/**
 *
 * @author Indi.An GmbH u. Co. KG / www.indi.an.com
 */
public class frmTCP extends javax.swing.JFrame {

	/** Creates new form frmTCP */
	public frmTCP() {
		initComponents();
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
	// <editor-fold defaultstate="collapsed" desc="Generated Code">
	private void initComponents() {

		jFrame1 = new javax.swing.JFrame();
		jPanel3 = new javax.swing.JPanel();
		jLabel1 = new javax.swing.JLabel();
		jLabel2 = new javax.swing.JLabel();
		jLabel3 = new javax.swing.JLabel();
		txtUser = new javax.swing.JTextField();
		txtSerial = new javax.swing.JTextField();
		jPanel5 = new javax.swing.JPanel();
		jLabel5 = new javax.swing.JLabel();
		txtIP = new javax.swing.JTextField();
		cmbPLCType = new javax.swing.JComboBox();
		jLabel6 = new javax.swing.JLabel();
		btnConnect = new javax.swing.JButton();
		btnDisConnect = new javax.swing.JButton();
		jLabel4 = new javax.swing.JLabel();
		txtState = new javax.swing.JTextField();
		jLabel13 = new javax.swing.JLabel();
		jLabel14 = new javax.swing.JLabel();
		txtRackID = new javax.swing.JTextField();
		txtSlotID = new javax.swing.JTextField();
		jPanel4 = new javax.swing.JPanel();
		jPanel6 = new javax.swing.JPanel();
		jLabel10 = new javax.swing.JLabel();
		jLabel11 = new javax.swing.JLabel();
		jLabel12 = new javax.swing.JLabel();
		jLabel9 = new javax.swing.JLabel();
		txtAdress = new javax.swing.JTextField();
		jLabel8 = new javax.swing.JLabel();
		cmbRegion = new javax.swing.JComboBox();
		txtStart = new javax.swing.JTextField();
		txtBit = new javax.swing.JTextField();
		txtLength = new javax.swing.JTextField();
		btnreadBit = new javax.swing.JButton();
		btnreadByte = new javax.swing.JButton();
		btnreadInt = new javax.swing.JButton();
		btnreadDINT = new javax.swing.JButton();
		btnreadWord = new javax.swing.JButton();
		btnreadReal = new javax.swing.JButton();
		btnwriteBit = new javax.swing.JButton();
		btnwriteByte = new javax.swing.JButton();
		btnwriteUniCodeChar = new javax.swing.JButton();
		btnwriteRawData = new javax.swing.JButton();
		btnwriteInt = new javax.swing.JButton();
		btnwriteREAL = new javax.swing.JButton();
		btnwriteDWord = new javax.swing.JButton();
		btnwriteBCD = new javax.swing.JButton();
		btnwriteWord = new javax.swing.JButton();
		btnwriteDInt = new javax.swing.JButton();
		btnreadDWord = new javax.swing.JButton();
		btnreadUniCodeChar = new javax.swing.JButton();
		btnreadRawData = new javax.swing.JButton();
		btnreadBCD = new javax.swing.JButton();
		btnreadCollection = new javax.swing.JButton();
		btngetCPUMode = new javax.swing.JButton();
		btngetPLCBasicInfo = new javax.swing.JButton();
		btnSetPLCTime = new javax.swing.JButton();
		btnGetPLCTime = new javax.swing.JButton();
		btnStopPLC = new javax.swing.JButton();
		btnStartPLC = new javax.swing.JButton();
		btngetPLCLEDInfo1 = new javax.swing.JButton();
		jPanel2 = new javax.swing.JPanel();
		jScrollPane1 = new javax.swing.JScrollPane();
		txtResult = new javax.swing.JTextArea();
		txtmessage = new javax.swing.JTextField();
		jLabel7 = new javax.swing.JLabel();

		javax.swing.GroupLayout jFrame1Layout = new javax.swing.GroupLayout(jFrame1.getContentPane());
		jFrame1.getContentPane().setLayout(jFrame1Layout);
		jFrame1Layout.setHorizontalGroup(jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGap(0, 400, Short.MAX_VALUE));
		jFrame1Layout.setVerticalGroup(jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGap(0, 300, Short.MAX_VALUE));

		setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
		addWindowListener(new java.awt.event.WindowAdapter() {
			public void windowOpened(java.awt.event.WindowEvent evt) {
				formWindowOpened(evt);
			}
		});
		getContentPane().setLayout(null);

		jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Serial"));
		jPanel3.setLayout(null);

		jLabel1.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
		jLabel1.setText("TCP ISO Example Enter Serial first >>>>>>>>>>");
		jPanel3.add(jLabel1);
		jLabel1.setBounds(30, 40, 393, 22);

		jLabel2.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
		jLabel2.setText("User");
		jPanel3.add(jLabel2);
		jLabel2.setBounds(560, 30, 23, 14);

		jLabel3.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
		jLabel3.setText("Serial");
		jPanel3.add(jLabel3);
		jLabel3.setBounds(560, 70, 27, 14);

		txtUser.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
		txtUser.setText("magna");
		txtUser.setPreferredSize(new java.awt.Dimension(156, 20));
		txtUser.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				txtUserActionPerformed(evt);
			}
		});
		jPanel3.add(txtUser);
		txtUser.setBounds(600, 30, 160, 20);

		txtSerial.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
		txtSerial.setText("86471-35181-102135-2966975");
		jPanel3.add(txtSerial);
		txtSerial.setBounds(600, 70, 160, 20);

		jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder("PLC-Propertys"));
		jPanel5.setLayout(null);

		jLabel5.setText("IP");
		jPanel5.add(jLabel5);
		jLabel5.setBounds(500, 60, 40, 16);

		txtIP.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
		txtIP.setText("192.168.0.10");
		jPanel5.add(txtIP);
		txtIP.setBounds(590, 60, 160, 20);

		cmbPLCType.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
		cmbPLCType.setModel(new javax.swing.DefaultComboBoxModel(new String[] {}));
		cmbPLCType.addItemListener(new java.awt.event.ItemListener() {
			public void itemStateChanged(java.awt.event.ItemEvent evt) {
				cmbPLCTypeItemStateChanged(evt);
			}
		});
		cmbPLCType.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				cmbPLCTypeActionPerformed(evt);
			}
		});
		jPanel5.add(cmbPLCType);
		cmbPLCType.setBounds(210, 20, 180, 20);

		jLabel6.setText("PLCTYPE");
		jPanel5.add(jLabel6);
		jLabel6.setBounds(150, 20, 60, 16);

		btnConnect.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
		btnConnect.setText("Connect");
		btnConnect.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				btnConnectActionPerformed(evt);
			}
		});
		jPanel5.add(btnConnect);
		btnConnect.setBounds(10, 20, 110, 23);

		btnDisConnect.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
		btnDisConnect.setText("DisConnect");
		btnDisConnect.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				btnDisConnectActionPerformed(evt);
			}
		});
		jPanel5.add(btnDisConnect);
		btnDisConnect.setBounds(10, 50, 110, 23);

		jLabel4.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
		jLabel4.setText("Connectionstatus");
		jPanel5.add(jLabel4);
		jLabel4.setBounds(500, 20, 84, 14);

		txtState.setEditable(false);
		txtState.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
		jPanel5.add(txtState);
		txtState.setBounds(590, 20, 160, 20);

		jLabel13.setText("Rack ID");
		jPanel5.add(jLabel13);
		jLabel13.setBounds(290, 50, 60, 20);

		jLabel14.setText("Slot ID");
		jPanel5.add(jLabel14);
		jLabel14.setBounds(292, 80, 50, 20);

		txtRackID.setText("0");
		jPanel5.add(txtRackID);
		txtRackID.setBounds(359, 50, 30, 22);

		txtSlotID.setText("2");
		jPanel5.add(txtSlotID);
		txtSlotID.setBounds(359, 80, 30, 22);

		jPanel3.add(jPanel5);
		jPanel5.setBounds(10, 100, 760, 110);

		getContentPane().add(jPanel3);
		jPanel3.setBounds(10, 0, 790, 220);

		javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
		jPanel4.setLayout(jPanel4Layout);
		jPanel4Layout.setHorizontalGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGap(0, 0, Short.MAX_VALUE));
		jPanel4Layout.setVerticalGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGap(0, 0, Short.MAX_VALUE));

		getContentPane().add(jPanel4);
		jPanel4.setBounds(0, 0, 0, 0);

		jPanel6.setBorder(javax.swing.BorderFactory.createTitledBorder("Access"));
		jPanel6.setLayout(null);

		jLabel10.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
		jLabel10.setText("Startadress (usually in Bytes)");
		jPanel6.add(jLabel10);
		jLabel10.setBounds(450, 90, 144, 14);

		jLabel11.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
		jLabel11.setText("Bit (only for Read Bits)");
		jPanel6.add(jLabel11);
		jLabel11.setBounds(490, 120, 109, 14);

		jLabel12.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
		jLabel12.setText("Length in Byte");
		jPanel6.add(jLabel12);
		jLabel12.setBounds(530, 150, 69, 14);

		jLabel9.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
		jLabel9.setText("DB (only for DB, use 0 oterwise)");
		jPanel6.add(jLabel9);
		jLabel9.setBounds(440, 60, 158, 14);

		txtAdress.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
		txtAdress.setText("1");
		jPanel6.add(txtAdress);
		txtAdress.setBounds(610, 60, 160, 20);

		jLabel8.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
		jLabel8.setText("Region");
		jPanel6.add(jLabel8);
		jLabel8.setBounds(560, 30, 33, 14);

		cmbRegion.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
		cmbRegion.setModel(new javax.swing.DefaultComboBoxModel(new String[] {}));
		cmbRegion.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				cmbRegionActionPerformed(evt);
			}
		});
		jPanel6.add(cmbRegion);
		cmbRegion.setBounds(610, 30, 160, 20);

		txtStart.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
		txtStart.setText("6");
		txtStart.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				txtStartActionPerformed(evt);
			}
		});
		jPanel6.add(txtStart);
		txtStart.setBounds(610, 90, 160, 20);

		txtBit.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
		txtBit.setText("0");
		jPanel6.add(txtBit);
		txtBit.setBounds(610, 120, 160, 20);

		txtLength.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
		txtLength.setText("4");
		jPanel6.add(txtLength);
		txtLength.setBounds(610, 150, 160, 20);

		btnreadBit.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
		btnreadBit.setText("read Bit");
		btnreadBit.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				btnreadBitActionPerformed(evt);
			}
		});
		jPanel6.add(btnreadBit);
		btnreadBit.setBounds(170, 20, 120, 23);

		btnreadByte.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
		btnreadByte.setText("read Byte");
		btnreadByte.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				btnreadByteActionPerformed(evt);
			}
		});
		jPanel6.add(btnreadByte);
		btnreadByte.setBounds(170, 50, 120, 23);

		btnreadInt.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
		btnreadInt.setText("read Int");
		btnreadInt.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				btnreadIntActionPerformed(evt);
			}
		});
		jPanel6.add(btnreadInt);
		btnreadInt.setBounds(170, 80, 120, 23);

		btnreadDINT.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
		btnreadDINT.setText("read DINT");
		btnreadDINT.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				btnreadDINTActionPerformed(evt);
			}
		});
		jPanel6.add(btnreadDINT);
		btnreadDINT.setBounds(170, 110, 120, 23);

		btnreadWord.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
		btnreadWord.setText("read Word");
		btnreadWord.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				btnreadWordActionPerformed(evt);
			}
		});
		jPanel6.add(btnreadWord);
		btnreadWord.setBounds(170, 140, 120, 23);

		btnreadReal.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
		btnreadReal.setText("read REAL");
		btnreadReal.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				btnreadRealActionPerformed(evt);
			}
		});
		jPanel6.add(btnreadReal);
		btnreadReal.setBounds(170, 200, 120, 23);

		btnwriteBit.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
		btnwriteBit.setText("write Bit");
		btnwriteBit.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				btnwriteBitActionPerformed(evt);
			}
		});
		jPanel6.add(btnwriteBit);
		btnwriteBit.setBounds(310, 20, 130, 23);

		btnwriteByte.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
		btnwriteByte.setText("write Byte");
		btnwriteByte.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				btnwriteByteActionPerformed(evt);
			}
		});
		jPanel6.add(btnwriteByte);
		btnwriteByte.setBounds(310, 50, 130, 23);

		btnwriteUniCodeChar.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
		btnwriteUniCodeChar.setText("write UniCodeChar");
		btnwriteUniCodeChar.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				btnwriteUniCodeCharActionPerformed(evt);
			}
		});
		jPanel6.add(btnwriteUniCodeChar);
		btnwriteUniCodeChar.setBounds(310, 260, 130, 23);

		btnwriteRawData.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
		btnwriteRawData.setText("write RawData");
		btnwriteRawData.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				btnwriteRawDataActionPerformed(evt);
			}
		});
		jPanel6.add(btnwriteRawData);
		btnwriteRawData.setBounds(310, 230, 130, 23);

		btnwriteInt.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
		btnwriteInt.setText("write Int");
		btnwriteInt.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				btnwriteIntActionPerformed(evt);
			}
		});
		jPanel6.add(btnwriteInt);
		btnwriteInt.setBounds(310, 80, 130, 23);

		btnwriteREAL.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
		btnwriteREAL.setText("write REAL");
		btnwriteREAL.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				btnwriteREALActionPerformed(evt);
			}
		});
		jPanel6.add(btnwriteREAL);
		btnwriteREAL.setBounds(310, 200, 130, 23);

		btnwriteDWord.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
		btnwriteDWord.setText("write DWord");
		btnwriteDWord.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				btnwriteDWordActionPerformed(evt);
			}
		});
		jPanel6.add(btnwriteDWord);
		btnwriteDWord.setBounds(310, 170, 130, 23);

		btnwriteBCD.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
		btnwriteBCD.setText("write BCD");
		btnwriteBCD.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				btnwriteBCDActionPerformed(evt);
			}
		});
		jPanel6.add(btnwriteBCD);
		btnwriteBCD.setBounds(310, 290, 130, 23);

		btnwriteWord.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
		btnwriteWord.setText("write Word");
		btnwriteWord.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				btnwriteWordActionPerformed(evt);
			}
		});
		jPanel6.add(btnwriteWord);
		btnwriteWord.setBounds(310, 140, 130, 23);

		btnwriteDInt.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
		btnwriteDInt.setText("write DINT");
		btnwriteDInt.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				btnwriteDIntActionPerformed(evt);
			}
		});
		jPanel6.add(btnwriteDInt);
		btnwriteDInt.setBounds(310, 110, 130, 23);

		btnreadDWord.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
		btnreadDWord.setText("read DWord");
		btnreadDWord.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				btnreadDWordActionPerformed(evt);
			}
		});
		jPanel6.add(btnreadDWord);
		btnreadDWord.setBounds(170, 170, 120, 23);

		btnreadUniCodeChar.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
		btnreadUniCodeChar.setText("read UniCodeChar");
		btnreadUniCodeChar.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				btnreadUniCodeCharActionPerformed(evt);
			}
		});
		jPanel6.add(btnreadUniCodeChar);
		btnreadUniCodeChar.setBounds(170, 260, 120, 23);

		btnreadRawData.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
		btnreadRawData.setText("read RawData");
		btnreadRawData.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				btnreadRawDataActionPerformed(evt);
			}
		});
		jPanel6.add(btnreadRawData);
		btnreadRawData.setBounds(170, 230, 120, 23);

		btnreadBCD.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
		btnreadBCD.setText("read BCD");
		btnreadBCD.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				btnreadBCDActionPerformed(evt);
			}
		});
		jPanel6.add(btnreadBCD);
		btnreadBCD.setBounds(170, 290, 120, 23);

		btnreadCollection.setBackground(new java.awt.Color(102, 255, 102));
		btnreadCollection.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
		btnreadCollection.setText("read Collection");
		btnreadCollection.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				btnreadCollectionActionPerformed(evt);
			}
		});
		jPanel6.add(btnreadCollection);
		btnreadCollection.setBounds(20, 290, 130, 23);

		btngetCPUMode.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
		btngetCPUMode.setText("get CPU Mode");
		btngetCPUMode.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				btngetCPUModeActionPerformed(evt);
			}
		});
		jPanel6.add(btngetCPUMode);
		btngetCPUMode.setBounds(20, 170, 130, 23);

		btngetPLCBasicInfo.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
		btngetPLCBasicInfo.setText("get PLC Basic Info");
		btngetPLCBasicInfo.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				btngetPLCBasicInfoActionPerformed(evt);
			}
		});
		jPanel6.add(btngetPLCBasicInfo);
		btngetPLCBasicInfo.setBounds(20, 140, 130, 23);

		btnSetPLCTime.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
		btnSetPLCTime.setText("Set PLC Time");
		btnSetPLCTime.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				btnSetPLCTimeActionPerformed(evt);
			}
		});
		jPanel6.add(btnSetPLCTime);
		btnSetPLCTime.setBounds(20, 110, 130, 23);

		btnGetPLCTime.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
		btnGetPLCTime.setText("Get PLC Time");
		btnGetPLCTime.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				btnGetPLCTimeActionPerformed(evt);
			}
		});
		jPanel6.add(btnGetPLCTime);
		btnGetPLCTime.setBounds(20, 80, 130, 23);

		btnStopPLC.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
		btnStopPLC.setText("Stop PLC");
		btnStopPLC.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				btnStopPLCActionPerformed(evt);
			}
		});
		jPanel6.add(btnStopPLC);
		btnStopPLC.setBounds(20, 50, 130, 23);

		btnStartPLC.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
		btnStartPLC.setText("Start PLC");
		btnStartPLC.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				btnStartPLCActionPerformed(evt);
			}
		});
		jPanel6.add(btnStartPLC);
		btnStartPLC.setBounds(20, 20, 130, 23);

		btngetPLCLEDInfo1.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
		btngetPLCLEDInfo1.setText("get PLC LED Info");
		btngetPLCLEDInfo1.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				btngetPLCLEDInfo1ActionPerformed(evt);
			}
		});
		jPanel6.add(btngetPLCLEDInfo1);
		btngetPLCLEDInfo1.setBounds(20, 200, 130, 23);

		getContentPane().add(jPanel6);
		jPanel6.setBounds(10, 220, 790, 320);

		jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Result"));
		jPanel2.setLayout(null);

		txtResult.setColumns(20);
		txtResult.setRows(5);
		jScrollPane1.setViewportView(txtResult);

		jPanel2.add(jScrollPane1);
		jScrollPane1.setBounds(10, 20, 760, 170);
		jPanel2.add(txtmessage);
		txtmessage.setBounds(10, 220, 760, 22);

		jLabel7.setText("Message");
		jPanel2.add(jLabel7);
		jLabel7.setBounds(10, 200, 50, 16);

		getContentPane().add(jPanel2);
		jPanel2.setBounds(10, 540, 790, 250);

		setSize(new java.awt.Dimension(826, 842));
		setLocationRelativeTo(null);
	}// </editor-fold>

	private TCP_ISO_Device Device = new TCP_ISO_Device("192.168.1.12", 0, 2, ePLCType.S7_200_compatibel);
	private Timer timer;

	private void btnConnectActionPerformed(java.awt.event.ActionEvent evt) {
		authentication.Serial(txtSerial.getText());
		authentication.User(txtUser.getText());
		Device.setPLCType(ePLCType.valueOf(cmbPLCType.getSelectedItem().toString()));
		Device.setIPAdress(txtIP.getText());
		Device.setRack(Integer.parseInt(txtRackID.getText()));
		Device.setSlot(Integer.parseInt(txtSlotID.getText()));
		Device.setConnecttimeout(1000);

		ConnectResult res = Device.Connect();
		if (!res.HasConnected()) {
			JOptionPane.showMessageDialog(null, res.Message(), "", JOptionPane.OK_CANCEL_OPTION);
		}

	}

	private void btnDisConnectActionPerformed(java.awt.event.ActionEvent evt) {
		Device.DisConnect();
	}

	private void formWindowOpened(java.awt.event.WindowEvent evt) {

		cmbPLCType.setModel(new javax.swing.DefaultComboBoxModel(ePLCTypeToStringArray()));
		cmbRegion.setModel(new javax.swing.DefaultComboBoxModel(eRegionToStringArray()));
		// Timer starten
		timer = new Timer();
		timer.schedule(new Task(), 1000, 1000);
		// timMain.Enabled = true;
	}

	private void cmbPLCTypeActionPerformed(java.awt.event.ActionEvent evt) {
		// TODO add your handling code here:
	}

	private void btnreadBitActionPerformed(java.awt.event.ActionEvent evt) {
		try {
			ReadRequest[] oRequest = new ReadRequest[1];
			oRequest[0] = new ReadRequest();

			oRequest[0].setRegion(eRegion.valueOf(cmbRegion.getSelectedItem().toString()));
			oRequest[0].setDB(Integer.valueOf(txtAdress.getText()));
			oRequest[0].setStartByte(Integer.valueOf(txtStart.getText()));
			oRequest[0].setLen(Integer.valueOf(txtLength.getText()));
			oRequest[0].setBit(Byte.valueOf(txtBit.getText()));
			oRequest[0].setIsBit(true);

			ReadResult[] res = Device.read(oRequest);
			txtmessage.setText(res[0].Message());
			txtResult.setText("");
			if (res[0].HasWorked() & res[0].DataAvailable()) {
				boolean[] readBuffer = res[0].Bufferbool();
				for (int i = 0; i <= res[0].BufferLen() - 1; i++) {
					txtResult.setText(
							txtResult.getText() + String.valueOf(readBuffer[i]) + System.getProperty("line.separator"));
				}
			}
			if (res[0].HasWorked() == true) {
				JOptionPane.showMessageDialog(null, "read successful", "", JOptionPane.INFORMATION_MESSAGE);
			} else {
				JOptionPane.showMessageDialog(null, "read unsuccessful", "", JOptionPane.ERROR_MESSAGE);
			}
		} catch (Exception ex) {
			Logger.getLogger(frmTCP.class.getName()).log(Level.SEVERE, null, ex);
		}
	}

	private void btnreadByteActionPerformed(java.awt.event.ActionEvent evt) {
		ReadRequest[] oRequest = new ReadRequest[1];
		oRequest[0] = new ReadRequest();

		oRequest[0].setRegion(eRegion.valueOf(cmbRegion.getSelectedItem().toString()));
		oRequest[0].setDB(Integer.valueOf(txtAdress.getText()));
		oRequest[0].setStartByte(Integer.valueOf(txtStart.getText()));
		oRequest[0].setLen(Integer.valueOf(txtLength.getText()));

		ReadResult[] res = Device.read(oRequest);
		txtmessage.setText(res[0].Message());
		txtResult.setText("");
		if (res[0].HasWorked() & res[0].DataAvailable()) {
			for (int i = 0; i <= res[0].BufferLen() - 1; i++) {
				txtResult.setText(
						txtResult.getText() + String.valueOf(res[0].get_Byte()) + System.getProperty("line.separator"));
			}
		}
		if (res[0].HasWorked() == true) {
			JOptionPane.showMessageDialog(null, "read successful", "", JOptionPane.INFORMATION_MESSAGE);
		} else {
			JOptionPane.showMessageDialog(null, "read unsuccessful", "", JOptionPane.ERROR_MESSAGE);
		}
	}

	private void btnreadIntActionPerformed(java.awt.event.ActionEvent evt) {
		ReadRequest[] oRequest = new ReadRequest[1];
		oRequest[0] = new ReadRequest();

		oRequest[0].setRegion(eRegion.valueOf(cmbRegion.getSelectedItem().toString()));
		oRequest[0].setDB(Integer.valueOf(txtAdress.getText()));
		oRequest[0].setStartByte(Integer.valueOf(txtStart.getText()));
		oRequest[0].setLen(Integer.valueOf(txtLength.getText()));

		ReadResult[] res = Device.read(oRequest);
		txtmessage.setText(res[0].Message());
		txtResult.setText("");
		if (res[0].HasWorked() & res[0].DataAvailable()) {
			while (res[0].DataAvailable()) {
				txtResult.setText(
						txtResult.getText() + String.valueOf(res[0].get_INT()) + System.getProperty("line.separator"));
			}
		}
		if (res[0].HasWorked() == true) {
			JOptionPane.showMessageDialog(null, "read successful", "", JOptionPane.INFORMATION_MESSAGE);
		} else {
			JOptionPane.showMessageDialog(null, "read unsuccessful", "", JOptionPane.ERROR_MESSAGE);
		}
	}

	private void btnreadDINTActionPerformed(java.awt.event.ActionEvent evt) {
		ReadRequest[] oRequest = new ReadRequest[1];
		oRequest[0] = new ReadRequest();

		oRequest[0].setRegion(eRegion.valueOf(cmbRegion.getSelectedItem().toString()));
		oRequest[0].setDB(Integer.valueOf(txtAdress.getText()));
		oRequest[0].setStartByte(Integer.valueOf(txtStart.getText()));
		oRequest[0].setLen(Integer.valueOf(txtLength.getText()));

		ReadResult[] res = Device.read(oRequest);
		txtmessage.setText(res[0].Message());
		txtResult.setText("");
		if (res[0].HasWorked() & res[0].DataAvailable()) {
			while (res[0].DataAvailable()) {
				txtResult.setText(
						txtResult.getText() + String.valueOf(res[0].get_DINT()) + System.getProperty("line.separator"));
			}
		}
		if (res[0].HasWorked() == true) {
			JOptionPane.showMessageDialog(null, "read successful", "", JOptionPane.INFORMATION_MESSAGE);
		} else {
			JOptionPane.showMessageDialog(null, "read unsuccessful", "", JOptionPane.ERROR_MESSAGE);
		}
	}

	private void btnreadWordActionPerformed(java.awt.event.ActionEvent evt) {
		ReadRequest[] oRequest = new ReadRequest[1];
		oRequest[0] = new ReadRequest();

		oRequest[0].setRegion(eRegion.valueOf(cmbRegion.getSelectedItem().toString()));
		oRequest[0].setDB(Integer.valueOf(txtAdress.getText()));
		oRequest[0].setStartByte(Integer.valueOf(txtStart.getText()));
		oRequest[0].setLen(Integer.valueOf(txtLength.getText()));

		ReadResult[] res = Device.read(oRequest);
		txtmessage.setText(res[0].Message());
		txtResult.setText("");
		if (res[0].HasWorked() & res[0].DataAvailable()) {
			while (res[0].DataAvailable()) {
				txtResult.setText(
						txtResult.getText() + String.valueOf(res[0].get_WORD()) + System.getProperty("line.separator"));
			}
		}
		if (res[0].HasWorked() == true) {
			JOptionPane.showMessageDialog(null, "read successful", "", JOptionPane.INFORMATION_MESSAGE);
		} else {
			JOptionPane.showMessageDialog(null, "read unsuccessful", "", JOptionPane.ERROR_MESSAGE);
		}
	}

	private void btnreadDWordActionPerformed(java.awt.event.ActionEvent evt) {
		ReadRequest[] oRequest = new ReadRequest[1];
		oRequest[0] = new ReadRequest();

		oRequest[0].setRegion(eRegion.valueOf(cmbRegion.getSelectedItem().toString()));
		oRequest[0].setDB(Integer.valueOf(txtAdress.getText()));
		oRequest[0].setStartByte(Integer.valueOf(txtStart.getText()));
		oRequest[0].setLen(Integer.valueOf(txtLength.getText()));

		ReadResult[] res = Device.read(oRequest);
		txtmessage.setText(res[0].Message());
		txtResult.setText("");
		if (res[0].HasWorked() & res[0].DataAvailable()) {
			while (res[0].DataAvailable()) {
				txtResult.setText(txtResult.getText() + String.valueOf(res[0].get_DWORD())
						+ System.getProperty("line.separator"));
			}
		}
		if (res[0].HasWorked() == true) {
			JOptionPane.showMessageDialog(null, "read successful", "", JOptionPane.INFORMATION_MESSAGE);
		} else {
			JOptionPane.showMessageDialog(null, "read unsuccessful", "", JOptionPane.ERROR_MESSAGE);
		}
	}

	private void btnreadRealActionPerformed(java.awt.event.ActionEvent evt) {
		ReadRequest[] oRequest = new ReadRequest[1];
		oRequest[0] = new ReadRequest();

		oRequest[0].setRegion(eRegion.valueOf(cmbRegion.getSelectedItem().toString()));
		oRequest[0].setDB(Integer.valueOf(txtAdress.getText()));
		oRequest[0].setStartByte(Integer.valueOf(txtStart.getText()));
		oRequest[0].setLen(Integer.valueOf(txtLength.getText()));

		ReadResult[] res = Device.read(oRequest);
		txtmessage.setText(res[0].Message());
		txtResult.setText("");
		if (res[0].HasWorked() & res[0].DataAvailable()) {
			while (res[0].DataAvailable()) {
				txtResult.setText(
						txtResult.getText() + String.valueOf(res[0].get_REAL()) + System.getProperty("line.separator"));
			}
		}
		if (res[0].HasWorked() == true) {
			JOptionPane.showMessageDialog(null, "read successful", "", JOptionPane.INFORMATION_MESSAGE);
		} else {
			JOptionPane.showMessageDialog(null, "read unsuccessful", "", JOptionPane.ERROR_MESSAGE);
		}
	}

	private void btnreadRawDataActionPerformed(java.awt.event.ActionEvent evt) {
		ReadRequest[] oRequest = new ReadRequest[1];
		oRequest[0] = new ReadRequest();

		oRequest[0].setRegion(eRegion.valueOf(cmbRegion.getSelectedItem().toString()));
		oRequest[0].setDB(Integer.valueOf(txtAdress.getText()));
		oRequest[0].setStartByte(Integer.valueOf(txtStart.getText()));
		oRequest[0].setLen(Integer.valueOf(txtLength.getText()));

		ReadResult[] res = Device.read(oRequest);
		txtmessage.setText(res[0].Message());
		txtResult.setText("");
		if (res[0].HasWorked() & res[0].DataAvailable()) {
			{
				byte[] readBuffer = (byte[]) res[0].Buffer();
				for (int i = 0; i <= res[0].BufferLen() - 1; i++) {
					txtResult.setText(
							txtResult.getText() + String.valueOf(readBuffer[i]) + System.getProperty("line.separator"));
				}
			}
		}
		if (res[0].HasWorked() == true) {
			JOptionPane.showMessageDialog(null, "read successful", "", JOptionPane.INFORMATION_MESSAGE);
		} else {
			JOptionPane.showMessageDialog(null, "read unsuccessful", "", JOptionPane.ERROR_MESSAGE);
		}
	}

	private void btnreadUniCodeCharActionPerformed(java.awt.event.ActionEvent evt) {
		ReadRequest[] oRequest = new ReadRequest[1];
		oRequest[0] = new ReadRequest();

		oRequest[0].setRegion(eRegion.valueOf(cmbRegion.getSelectedItem().toString()));
		oRequest[0].setDB(Integer.valueOf(txtAdress.getText()));
		oRequest[0].setStartByte(Integer.valueOf(txtStart.getText()));
		oRequest[0].setLen(Integer.valueOf(txtLength.getText()));

		ReadResult[] res = Device.read(oRequest);
		txtmessage.setText(res[0].Message());
		txtResult.setText("");
		if (res[0].HasWorked() & res[0].DataAvailable()) {
			while (res[0].DataAvailable()) {
				txtResult.setText(txtResult.getText() + String.valueOf(res[0].get_UniCodeChar())
						+ System.getProperty("line.separator"));
			}
		}
		if (res[0].HasWorked() == true) {
			JOptionPane.showMessageDialog(null, "read successful", "", JOptionPane.INFORMATION_MESSAGE);
		} else {
			JOptionPane.showMessageDialog(null, "read unsuccessful", "", JOptionPane.ERROR_MESSAGE);
		}
	}

	private void btnreadBCDActionPerformed(java.awt.event.ActionEvent evt) {
		ReadRequest[] oRequest = new ReadRequest[1];
		oRequest[0] = new ReadRequest();

		oRequest[0].setRegion(eRegion.valueOf(cmbRegion.getSelectedItem().toString()));
		oRequest[0].setDB(Integer.valueOf(txtAdress.getText()));
		oRequest[0].setStartByte(Integer.valueOf(txtStart.getText()));
		oRequest[0].setLen(Integer.valueOf(txtLength.getText()));

		ReadResult[] res = Device.read(oRequest);
		txtmessage.setText(res[0].Message());
		txtResult.setText("");
		if (res[0].HasWorked() & res[0].DataAvailable()) {
			while (res[0].DataAvailable()) {
				txtResult.setText(txtResult.getText() + String.valueOf(res[0].get_BCD16())
						+ System.getProperty("line.separator"));
			}
		}
		if (res[0].HasWorked() == true) {
			JOptionPane.showMessageDialog(null, "read successful", "", JOptionPane.INFORMATION_MESSAGE);
		} else {
			JOptionPane.showMessageDialog(null, "read unsuccessful", "", JOptionPane.ERROR_MESSAGE);
		}
	}

	private void btnwriteBitActionPerformed(java.awt.event.ActionEvent evt) {
		WriteRequest[] oWriteRequest = new WriteRequest[1];
		oWriteRequest[0] = new WriteRequest();
		oWriteRequest[0].setRegion(eRegion.valueOf(cmbRegion.getSelectedItem().toString()));
		oWriteRequest[0].setDB(Integer.valueOf(txtAdress.getText()));
		oWriteRequest[0].setStartByte(Integer.valueOf(txtStart.getText()));
		oWriteRequest[0].setBit(Byte.valueOf(txtBit.getText()));

		oWriteRequest[0].addBit(true);
		// add writable Data here
		WriteResult[] res = Device.write(oWriteRequest);
		// write
		txtmessage.setText(res[0].Message());
		if (res[0].HasWorked() == true) {
			JOptionPane.showMessageDialog(null, "write successful", "", JOptionPane.INFORMATION_MESSAGE);
		} else {
			JOptionPane.showMessageDialog(null, "write unsuccessful", "", JOptionPane.ERROR_MESSAGE);
		}
	}

	private void btnwriteByteActionPerformed(java.awt.event.ActionEvent evt) {
		WriteRequest[] oWriteRequest = new WriteRequest[1];
		oWriteRequest[0] = new WriteRequest();
		oWriteRequest[0].setRegion(eRegion.valueOf(cmbRegion.getSelectedItem().toString()));
		oWriteRequest[0].setDB(Integer.valueOf(txtAdress.getText()));
		oWriteRequest[0].setStartByte(Integer.valueOf(txtStart.getText()));
		// Write 3 bytes
		byte[] b = { (byte) 9, (byte) 153 };
		oWriteRequest[0].addByte(b);
		// add writable Data as array
		oWriteRequest[0].addByte((byte) 255);
		// add writable Data as value

		WriteResult[] res = Device.write(oWriteRequest);
		// write
		txtmessage.setText(res[0].Message());
		if (res[0].HasWorked() == true) {
			JOptionPane.showMessageDialog(null, "write successful", "", JOptionPane.INFORMATION_MESSAGE);
		} else {
			JOptionPane.showMessageDialog(null, "write unsuccessful", "", JOptionPane.ERROR_MESSAGE);
		}
	}

	private void btnwriteIntActionPerformed(java.awt.event.ActionEvent evt) {
		WriteRequest[] oWriteRequest = new WriteRequest[1];
		oWriteRequest[0] = new WriteRequest();
		oWriteRequest[0].setRegion(eRegion.valueOf(cmbRegion.getSelectedItem().toString()));
		oWriteRequest[0].setDB(Integer.valueOf(txtAdress.getText()));
		oWriteRequest[0].setStartByte(Integer.valueOf(txtStart.getText()));

		int[] b = { 4584, -9851 };
		oWriteRequest[0].addInt(b);
		// add writable Data as array
		oWriteRequest[0].addInt(Short.MAX_VALUE);
		// add writable Data as value

		WriteResult[] res = Device.write(oWriteRequest);
		// write
		txtmessage.setText(res[0].Message());
		if (res[0].HasWorked() == true) {
			JOptionPane.showMessageDialog(null, "write successful", "", JOptionPane.INFORMATION_MESSAGE);
		} else {
			JOptionPane.showMessageDialog(null, "write unsuccessful", "", JOptionPane.ERROR_MESSAGE);
		}
	}

	private void btnwriteDIntActionPerformed(java.awt.event.ActionEvent evt) {
		WriteRequest[] oWriteRequest = new WriteRequest[1];
		oWriteRequest[0] = new WriteRequest();
		oWriteRequest[0].setRegion(eRegion.valueOf(cmbRegion.getSelectedItem().toString()));
		oWriteRequest[0].setDB(Integer.valueOf(txtAdress.getText()));
		oWriteRequest[0].setStartByte(Integer.valueOf(txtStart.getText()));

		long[] b = { 123456, -123456 };
		oWriteRequest[0].addDInt(b);
		// add writable Data as array
		oWriteRequest[0].addDInt(Integer.MAX_VALUE);
		// add writable Data as value

		WriteResult[] res = Device.write(oWriteRequest);
		// write
		txtmessage.setText(res[0].Message());
		if (res[0].HasWorked() == true) {
			JOptionPane.showMessageDialog(null, "write successful", "", JOptionPane.INFORMATION_MESSAGE);
		} else {
			JOptionPane.showMessageDialog(null, "write unsuccessful", "", JOptionPane.ERROR_MESSAGE);
		}
	}

	private void btnwriteWordActionPerformed(java.awt.event.ActionEvent evt) {
		WriteRequest[] oWriteRequest = new WriteRequest[1];
		oWriteRequest[0] = new WriteRequest();
		oWriteRequest[0].setRegion(eRegion.valueOf(cmbRegion.getSelectedItem().toString()));
		oWriteRequest[0].setDB(Integer.valueOf(txtAdress.getText()));
		oWriteRequest[0].setStartByte(Integer.valueOf(txtStart.getText()));

		int[] b = { 12356, 11 };
		oWriteRequest[0].addWord(b);
		// add writable Data as array
		oWriteRequest[0].addWord(Short.MAX_VALUE);
		// add writable Data as value

		WriteResult[] res = Device.write(oWriteRequest);
		// write
		txtmessage.setText(res[0].Message());
		if (res[0].HasWorked() == true) {
			JOptionPane.showMessageDialog(null, "write successful", "", JOptionPane.INFORMATION_MESSAGE);
		} else {
			JOptionPane.showMessageDialog(null, "write unsuccessful", "", JOptionPane.ERROR_MESSAGE);
		}
	}

	private void btnwriteDWordActionPerformed(java.awt.event.ActionEvent evt) {
		WriteRequest[] oWriteRequest = new WriteRequest[1];
		oWriteRequest[0] = new WriteRequest();
		oWriteRequest[0].setRegion(eRegion.valueOf(cmbRegion.getSelectedItem().toString()));
		oWriteRequest[0].setDB(Integer.valueOf(txtAdress.getText()));
		oWriteRequest[0].setStartByte(Integer.valueOf(txtStart.getText()));

		long[] b = { 12356, 11 };
		oWriteRequest[0].addDWord(b);
		// add writable Data as array
		oWriteRequest[0].addDWord(Long.MAX_VALUE);
		// add writable Data as value

		WriteResult[] res = Device.write(oWriteRequest);
		// write
		txtmessage.setText(res[0].Message());
		if (res[0].HasWorked() == true) {
			JOptionPane.showMessageDialog(null, "write successful", "", JOptionPane.INFORMATION_MESSAGE);
		} else {
			JOptionPane.showMessageDialog(null, "write unsuccessful", "", JOptionPane.ERROR_MESSAGE);
		}
	}

	private void btnwriteREALActionPerformed(java.awt.event.ActionEvent evt) {
		WriteRequest[] oWriteRequest = new WriteRequest[1];
		oWriteRequest[0] = new WriteRequest();
		oWriteRequest[0].setRegion(eRegion.valueOf(cmbRegion.getSelectedItem().toString()));
		oWriteRequest[0].setDB(Integer.valueOf(txtAdress.getText()));
		oWriteRequest[0].setStartByte(Integer.valueOf(txtStart.getText()));

		float[] b = { (float) 12356.123, (float) -11.55 };
		oWriteRequest[0].addReal(b);
		// add writable Data as array
		oWriteRequest[0].addReal(Float.MAX_VALUE);
		// add writable Data as value

		WriteResult[] res = Device.write(oWriteRequest);
		// write
		txtmessage.setText(res[0].Message());
		if (res[0].HasWorked() == true) {
			JOptionPane.showMessageDialog(null, "write successful", "", JOptionPane.INFORMATION_MESSAGE);
		} else {
			JOptionPane.showMessageDialog(null, "write unsuccessful", "", JOptionPane.ERROR_MESSAGE);
		}
	}

	private void btnwriteRawDataActionPerformed(java.awt.event.ActionEvent evt) {
		WriteRequest[] oWriteRequest = new WriteRequest[1];
		oWriteRequest[0] = new WriteRequest();
		oWriteRequest[0].setRegion(eRegion.valueOf(cmbRegion.getSelectedItem().toString()));
		oWriteRequest[0].setDB(Integer.valueOf(txtAdress.getText()));
		oWriteRequest[0].setStartByte(Integer.valueOf(txtStart.getText()));

		byte[] b = { 1, 2, 3, Byte.MAX_VALUE };
		oWriteRequest[0].setBuffer(b);
		// add writable Data as Bytearray

		WriteResult[] res = Device.write(oWriteRequest);
		// write
		txtmessage.setText(res[0].Message());
		if (res[0].HasWorked() == true) {
			JOptionPane.showMessageDialog(null, "write successful", "", JOptionPane.INFORMATION_MESSAGE);
		} else {
			JOptionPane.showMessageDialog(null, "write unsuccessful", "", JOptionPane.ERROR_MESSAGE);
		}
	}

	private void btnwriteUniCodeCharActionPerformed(java.awt.event.ActionEvent evt) {
		WriteRequest[] oWriteRequest = new WriteRequest[1];
		oWriteRequest[0] = new WriteRequest();
		oWriteRequest[0].setRegion(eRegion.valueOf(cmbRegion.getSelectedItem().toString()));
		oWriteRequest[0].setDB(Integer.valueOf(txtAdress.getText()));
		oWriteRequest[0].setStartByte(Integer.valueOf(txtStart.getText()));

		char[] b = { 'a', 'b', 'c' };
		oWriteRequest[0].addUniCodeChar(b);
		// add writable Data as array
		oWriteRequest[0].addUniCodeChar('d');
		// add writable Data as value

		WriteResult[] res = Device.write(oWriteRequest);
		// write
		txtmessage.setText(res[0].Message());
		if (res[0].HasWorked() == true) {
			JOptionPane.showMessageDialog(null, "write successful", "", JOptionPane.INFORMATION_MESSAGE);
		} else {
			JOptionPane.showMessageDialog(null, "write unsuccessful", "", JOptionPane.ERROR_MESSAGE);
		}
	}

	private void btnwriteBCDActionPerformed(java.awt.event.ActionEvent evt) {
		WriteRequest[] oWriteRequest = new WriteRequest[1];
		oWriteRequest[0] = new WriteRequest();
		oWriteRequest[0].setRegion(eRegion.valueOf(cmbRegion.getSelectedItem().toString()));
		oWriteRequest[0].setDB(Integer.valueOf(txtAdress.getText()));
		oWriteRequest[0].setStartByte(Integer.valueOf(txtStart.getText()));

		short[] b = { 1234, 4568 };
		oWriteRequest[0].addBCD16(b);
		// add writable Data as array
		oWriteRequest[0].addBCD16((short) 9999);
		// add writable Data as value

		WriteResult[] res = Device.write(oWriteRequest);
		// write
		txtmessage.setText(res[0].Message());
		if (res[0].HasWorked() == true) {
			JOptionPane.showMessageDialog(null, "write successful", "", JOptionPane.INFORMATION_MESSAGE);
		} else {
			JOptionPane.showMessageDialog(null, "write unsuccessful", "", JOptionPane.ERROR_MESSAGE);
		}
	}

	private void cmbRegionActionPerformed(java.awt.event.ActionEvent evt) {
		// TODO add your handling code here:
	}

	private void txtUserActionPerformed(java.awt.event.ActionEvent evt) {
		// TODO add your handling code here:
	}

	private void btnreadCollectionActionPerformed(java.awt.event.ActionEvent evt) {
		try {
			JOptionPane.showMessageDialog(null,
					"before you could use the 'Read Collection' option, you have to configure the marked region (Edit Collection) code-area!",
					"", JOptionPane.INFORMATION_MESSAGE);

			ReadItemRequestCollection oReadItemRequestCollection = new ReadItemRequestCollection();
			ReadItemRequest oReadItemRequest = new ReadItemRequest();

			// <editor-fold defaultstate="collapsed" desc="Edit Collection
			// oReadItemRequest">

			oReadItemRequest.setRegion(eRegion.DataBlock);
			oReadItemRequest.setDB(204);
			oReadItemRequest.setStartByte(610);
			oReadItemRequest.setQuantity(5);
			oReadItemRequest.setBit((byte) 1);
			oReadItemRequest.setDataType(eDataType.BIT);
			oReadItemRequest.setItemkey("Item1");
			oReadItemRequestCollection.addReadItemRequest(oReadItemRequest);

			oReadItemRequest = new ReadItemRequest();
			oReadItemRequest.setRegion(eRegion.DataBlock);
			oReadItemRequest.setDB(204);
			oReadItemRequest.setStartByte(4);
			oReadItemRequest.setQuantity(20);
			oReadItemRequest.setDataType(eDataType.BYTE);
			oReadItemRequest.setItemkey("Item2");
			oReadItemRequestCollection.addReadItemRequest(oReadItemRequest);

			oReadItemRequest = new ReadItemRequest();
			oReadItemRequest.setRegion(eRegion.DataBlock);
			oReadItemRequest.setDB(204);
			oReadItemRequest.setStartByte(240);
			oReadItemRequest.setQuantity(23);
			oReadItemRequest.setBit((byte) 0);
			oReadItemRequest.setDataType(eDataType.BYTE);
			oReadItemRequest.setItemkey("Item3");
			oReadItemRequestCollection.addReadItemRequest(oReadItemRequest);

			// </editor-fold>

			oReadItemRequestCollection.setOptmize(true);

			ReadItemResultCollection oReadItemResultCollection = Device.read(oReadItemRequestCollection);

			Boolean[] isItemAvalible = new Boolean[1];

			// Option 1 >>> find Itemresult with keyname
			ReadItemResult res1 = oReadItemResultCollection.getReadItemResult("Item1", isItemAvalible);
			ReadItemResult res2 = oReadItemResultCollection.getReadItemResult("Item2", isItemAvalible);
			ReadItemResult res3 = oReadItemResultCollection.getReadItemResult("Item3", isItemAvalible);

			// Option2 >>> find itemresult with foreach-loop
			for (ReadItemResult res : oReadItemResultCollection.getReadItemResult()) {
				StringBuilder sb = new StringBuilder();
				Object[] val = new Object[1];
				if (res.HasWorked()) {
					val = (Object[]) res.getValue();
					for (int i = 0; i < val.length; i++) {
						sb.append(val[i].toString());
						sb.append(String.format("%n"));
					}
				}

				if (res.HasWorked() == true) {
					JOptionPane.showMessageDialog(null,
							"read " + res.Itemkey() + " successful" + String.format("%n") + sb.toString(), "",
							JOptionPane.INFORMATION_MESSAGE);
				} else {
					JOptionPane.showMessageDialog(null,
							"read " + res.Itemkey() + " unsuccessful" + String.format("%n") + res.Message(), "",
							JOptionPane.INFORMATION_MESSAGE);
				}
			}
		} catch (Exception ex) {
			Logger.getLogger(frmTCP.class.getName()).log(Level.SEVERE, null, ex);
		}
	}

	private void btnStartPLCActionPerformed(java.awt.event.ActionEvent evt) {
		OperationResult res = Device.StartPLC();
		txtmessage.setText(res.Message());
		if (res.HasWorked() == true) {
			JOptionPane.showMessageDialog(null, "operation successful", "", JOptionPane.INFORMATION_MESSAGE);
		} else {
			JOptionPane.showMessageDialog(null, "operation unsuccessful", "", JOptionPane.ERROR_MESSAGE);
		}
	}

	private void btnStopPLCActionPerformed(java.awt.event.ActionEvent evt) {
		OperationResult res = Device.StopPLC();
		txtmessage.setText(res.Message());
		if (res.HasWorked() == true) {
			JOptionPane.showMessageDialog(null, "operation successful", "", JOptionPane.INFORMATION_MESSAGE);
		} else {
			JOptionPane.showMessageDialog(null, "operation unsuccessful", "", JOptionPane.ERROR_MESSAGE);
		}
	}

	private void btnGetPLCTimeActionPerformed(java.awt.event.ActionEvent evt) {
		ReadResult res = Device.GetPLCTime();
		txtmessage.setText(res.Message());
		if (res.HasWorked() == true) {
			SimpleDateFormat SDF = new SimpleDateFormat("dd.MM.yyyy HH:mm:ss");
			Calendar c = res.get_DATE_AND_TIME();
			JOptionPane.showMessageDialog(null, SDF.format(c.getTime()), "", JOptionPane.INFORMATION_MESSAGE);
		}
	}

	private void btnSetPLCTimeActionPerformed(java.awt.event.ActionEvent evt) {
		Calendar now = new GregorianCalendar();
		now.set(Calendar.HOUR_OF_DAY, now.get(Calendar.HOUR_OF_DAY) - 0);
		WriteResult res = Device.SetPLCTime(now);
		txtmessage.setText(res.Message());
		if (res.HasWorked()) {
			JOptionPane.showMessageDialog(null, "operation successful", "", JOptionPane.INFORMATION_MESSAGE);
		} else {
			JOptionPane.showMessageDialog(null, "operation unsuccessful", "", JOptionPane.ERROR_MESSAGE);
		}
	}

	private void btngetCPUModeActionPerformed(java.awt.event.ActionEvent evt) {
		CPUModeInfoResult res = Device.GetCPUMode();
		txtmessage.setText(res.Message());
		if (res.HasWorked()) {
			String CPUModetext = "PLCMode: " + String.valueOf(res.CPUModeInfo());
			JOptionPane.showMessageDialog(null, CPUModetext, "", JOptionPane.INFORMATION_MESSAGE);
		} else {
			JOptionPane.showMessageDialog(null, "operation unsuccessful", "", JOptionPane.ERROR_MESSAGE);
		}
	}

	private void btngetPLCBasicInfoActionPerformed(java.awt.event.ActionEvent evt) {
		BasicInfoResult res = Device.GetBasicInfo();
		txtmessage.setText(res.Message());
		if (res.HasWorked()) {
			JOptionPane.showMessageDialog(null,
					res.Ordernummer() + " " + res.ModuleVersion() + " " + res.Name() + " " + res.FirmwareVersion(), "",
					JOptionPane.INFORMATION_MESSAGE);
		} else {
			JOptionPane.showMessageDialog(null, "operation unsuccessful", "", JOptionPane.ERROR_MESSAGE);
		}
	}

	private void cmbPLCTypeItemStateChanged(java.awt.event.ItemEvent evt) {
		if (cmbPLCType.getSelectedItem().toString().equalsIgnoreCase(ePLCType.S7_200_compatibel.toString())) {
			txtSlotID.setText("0");
			txtRackID.setText("0");
		}
		if (cmbPLCType.getSelectedItem().toString().equalsIgnoreCase(ePLCType.S7_300_400_compatibel.toString())) {
			txtSlotID.setText("2");
			txtRackID.setText("0");
		}
		if (cmbPLCType.getSelectedItem().toString().equalsIgnoreCase(ePLCType.S7_1200_compatibel.toString())) {
			txtSlotID.setText("0");
			txtRackID.setText("0");
		}
		if (cmbPLCType.getSelectedItem().toString().equalsIgnoreCase(ePLCType.Other.toString())) {
			txtSlotID.setText("");
			txtRackID.setText("");
		}
	}

	private void txtStartActionPerformed(java.awt.event.ActionEvent evt) {
		// TODO add your handling code here:
	}

	private void btngetPLCLEDInfo1ActionPerformed(java.awt.event.ActionEvent evt) {

		LEDInfoResult res = Device.GetLEDInfo();
		txtmessage.setText(res.Message());
		if (res.HasWorked() == true) {
			StringBuilder sb = new StringBuilder();
			for (int i = 0; i < res.LEDInfo().length; i++) {
				sb.append("LED= " + String.valueOf(res.LEDInfo()[i].identifier) + " State= "
						+ String.valueOf(res.LEDInfo()[i].state) + " flashingstate= "
						+ String.valueOf(res.LEDInfo()[i].flashing) + System.getProperty("line.separator"));
			}
			JOptionPane.showMessageDialog(null, sb.toString(), "", JOptionPane.INFORMATION_MESSAGE);
		} else {
			JOptionPane.showMessageDialog(null, "operation unsuccessful", "", JOptionPane.ERROR_MESSAGE);
		}
	}

	static String[] ePLCTypeToStringArray() {
		String[] results = new String[ePLCType.values().length];
		int count = 0;
		for (ePLCType each : ePLCType.values()) {
			results[count] = each.toString();
			count++;
		}
		return results;
	}

	static String[] eRegionToStringArray() {
		String[] results = new String[eRegion.values().length];
		int count = 0;
		for (eRegion each : eRegion.values()) {
			results[count] = each.toString();
			count++;
		}
		return results;
	}

	/**
	 * @param args
	 *            the command line arguments
	 */
	public static void main(String args[]) {
		java.awt.EventQueue.invokeLater(new Runnable() {

			public void run() {
				new frmTCP().setVisible(true);
			}
		});
	}

	// Variables declaration - do not modify
	private javax.swing.JButton btnConnect;
	private javax.swing.JButton btnDisConnect;
	private javax.swing.JButton btnGetPLCTime;
	private javax.swing.JButton btnSetPLCTime;
	private javax.swing.JButton btnStartPLC;
	private javax.swing.JButton btnStopPLC;
	private javax.swing.JButton btngetCPUMode;
	private javax.swing.JButton btngetPLCBasicInfo;
	private javax.swing.JButton btngetPLCLEDInfo1;
	private javax.swing.JButton btnreadBCD;
	private javax.swing.JButton btnreadBit;
	private javax.swing.JButton btnreadByte;
	private javax.swing.JButton btnreadCollection;
	private javax.swing.JButton btnreadDINT;
	private javax.swing.JButton btnreadDWord;
	private javax.swing.JButton btnreadInt;
	private javax.swing.JButton btnreadRawData;
	private javax.swing.JButton btnreadReal;
	private javax.swing.JButton btnreadUniCodeChar;
	private javax.swing.JButton btnreadWord;
	private javax.swing.JButton btnwriteBCD;
	private javax.swing.JButton btnwriteBit;
	private javax.swing.JButton btnwriteByte;
	private javax.swing.JButton btnwriteDInt;
	private javax.swing.JButton btnwriteDWord;
	private javax.swing.JButton btnwriteInt;
	private javax.swing.JButton btnwriteREAL;
	private javax.swing.JButton btnwriteRawData;
	private javax.swing.JButton btnwriteUniCodeChar;
	private javax.swing.JButton btnwriteWord;
	private javax.swing.JComboBox cmbPLCType;
	private javax.swing.JComboBox cmbRegion;
	private javax.swing.JFrame jFrame1;
	private javax.swing.JLabel jLabel1;
	private javax.swing.JLabel jLabel10;
	private javax.swing.JLabel jLabel11;
	private javax.swing.JLabel jLabel12;
	private javax.swing.JLabel jLabel13;
	private javax.swing.JLabel jLabel14;
	private javax.swing.JLabel jLabel2;
	private javax.swing.JLabel jLabel3;
	private javax.swing.JLabel jLabel4;
	private javax.swing.JLabel jLabel5;
	private javax.swing.JLabel jLabel6;
	private javax.swing.JLabel jLabel7;
	private javax.swing.JLabel jLabel8;
	private javax.swing.JLabel jLabel9;
	private javax.swing.JPanel jPanel2;
	private javax.swing.JPanel jPanel3;
	private javax.swing.JPanel jPanel4;
	private javax.swing.JPanel jPanel5;
	private javax.swing.JPanel jPanel6;
	private javax.swing.JScrollPane jScrollPane1;
	private javax.swing.JTextField txtAdress;
	private javax.swing.JTextField txtBit;
	private javax.swing.JTextField txtIP;
	private javax.swing.JTextField txtLength;
	private javax.swing.JTextField txtRackID;
	private javax.swing.JTextArea txtResult;
	private javax.swing.JTextField txtSerial;
	private javax.swing.JTextField txtSlotID;
	private javax.swing.JTextField txtStart;
	private javax.swing.JTextField txtState;
	private javax.swing.JTextField txtUser;
	private javax.swing.JTextField txtmessage;
	// End of variables declaration

	class Task extends TimerTask {

		@Override
		public void run() {

			try {
				txtState.setText("Connected = " + String.valueOf(Device.IsConnected()));
				// Längenangabe korrigiert --> Daten ok
				// dc.readBytes(PLCCom.Nodave.DB, 204, 0, 8, null);
				// b = dc.getINT();

				// Eingaben auswerten
				// int Start = 0;
				// int Laenge= 0;
				// int DB = 0;
				// byte[] buffer1;

				// DB = Integer.parseInt(jTextField4.getText());
				// Start = Integer.parseInt(jTextField5.getText());
				// Laenge = Integer.parseInt(jTextField6.getText());
				// buffer1 = new byte[Laenge];
				//
				// dc.readBytes(PLCCom.Nodave.DB, DB, Start, Laenge, buffer1);
				// //dc.writeBytes(PLCCom.Nodave.DB, DB, Start, Laenge, buffer1)
				// dc.getFloat();
				// setAusgabeText(Long.toString(a));
				// } catch (Exception e) {
				// jTextArea1.append(e.toString() + newline);
			} finally {
			}
		}
	}
}
